//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAYW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AAYW.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin page.
        /// </summary>
        internal static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contorols.
        /// </summary>
        internal static string Contorols {
            get {
                return ResourceManager.GetString("Contorols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom forms.
        /// </summary>
        internal static string CustomForms {
            get {
                return ResourceManager.GetString("CustomForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity editor.
        /// </summary>
        internal static string EntityEditor {
            get {
                return ResourceManager.GetString("EntityEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity inspector.
        /// </summary>
        internal static string EntityInspector {
            get {
                return ResourceManager.GetString("EntityInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on row to edit.
        /// </summary>
        internal static string EntityInspectorHint {
            get {
                return ResourceManager.GetString("EntityInspectorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not registered.
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} must be equal.
        /// </summary>
        internal static string Error_Compare {
            get {
                return ResourceManager.GetString("Error_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be shorter than {1} characters and longer than {2}.
        /// </summary>
        internal static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 403.
        /// </summary>
        internal static string Error_NotAllowed {
            get {
                return ResourceManager.GetString("Error_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access level is low..
        /// </summary>
        internal static string Error_NotAllowedDetails {
            get {
                return ResourceManager.GetString("Error_NotAllowedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested page or resource not found. Sorry..
        /// </summary>
        internal static string Error_NotFoundDetails {
            get {
                return ResourceManager.GetString("Error_NotFoundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with this name already exist.
        /// </summary>
        internal static string Error_TemplateExist {
            get {
                return ResourceManager.GetString("Error_TemplateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url must be uniue.
        /// </summary>
        internal static string Error_UrlMustBeUniue {
            get {
                return ResourceManager.GetString("Error_UrlMustBeUniue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string FailedToLogin {
            get {
                return ResourceManager.GetString("FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string FormSubmited {
            get {
                return ResourceManager.GetString("FormSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been sent!.
        /// </summary>
        internal static string FormSubmitedDetails {
            get {
                return ResourceManager.GetString("FormSubmitedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here because you&apos;re visiting site first time or home page not set. To set homepage navigate to Admin Page and create page with URL &quot;home&quot;..
        /// </summary>
        internal static string LandingDetails {
            get {
                return ResourceManager.GetString("LandingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAYW -- is a fast way to create customizeble site..
        /// </summary>
        internal static string LandingExplanation {
            get {
                return ResourceManager.GetString("LandingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AAYW..
        /// </summary>
        internal static string LandingWelcome {
            get {
                return ResourceManager.GetString("LandingWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250x250, PNG, Transparent background..
        /// </summary>
        internal static string LogoBig_Recomendations {
            get {
                return ResourceManager.GetString("LogoBig_Recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64x64, PNG, Transparent background..
        /// </summary>
        internal static string LogoSmall_Recomendations {
            get {
                return ResourceManager.GetString("LogoSmall_Recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail adress.
        /// </summary>
        internal static string MailAdress {
            get {
                return ResourceManager.GetString("MailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        internal static string MailEnableSsl {
            get {
                return ResourceManager.GetString("MailEnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail host.
        /// </summary>
        internal static string MailHost {
            get {
                return ResourceManager.GetString("MailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail password.
        /// </summary>
        internal static string MailPassword {
            get {
                return ResourceManager.GetString("MailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail port.
        /// </summary>
        internal static string MailPort {
            get {
                return ResourceManager.GetString("MailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail settings.
        /// </summary>
        internal static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail template.
        /// </summary>
        internal static string MailTemplateCreate {
            get {
                return ResourceManager.GetString("MailTemplateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail templates.
        /// </summary>
        internal static string MailTemplates {
            get {
                return ResourceManager.GetString("MailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail username.
        /// </summary>
        internal static string MailUsername {
            get {
                return ResourceManager.GetString("MailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        internal static string UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserAlreadyRegistered", resourceCulture);
            }
        }
    }
}
